apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-booking-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sports-booking-backend
  template:
    metadata:
      labels:
        app: sports-booking-backend
    spec:
      containers:
      - name: sports-booking-backend
        image: yourusername/sports-booking-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: sports-booking-secrets
              key: mongodb-uri
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: sports-booking-secrets
              key: jwt-secret
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sports-booking-secrets
              key: sentry-dsn
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 