apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: sports-booking
type: Opaque
data:
  mongodb-root-password: cm9vdHBhc3N3b3Jk
  mongodb-password: cGFzc3dvcmQ=
  mongodb-replica-set-key: cmVwbGljYXNldGtleQ== 