apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: sports-booking
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb 