apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: sports-booking
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: nginx 