apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sports-booking-data
  namespace: sports-booking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard 