apiVersion: v1
kind: Secret
metadata:
  name: sports-booking-secrets
type: Opaque
data:
  mongodb-uri: base64_encoded_mongodb_uri
  jwt-secret: base64_encoded_jwt_secret
  sentry-dsn: base64_encoded_sentry_dsn 