apiVersion: v1
kind: Service
metadata:
  name: sentry
  namespace: sentry
  labels:
    app: sentry
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    name: http
  selector:
    app: sentry 