apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentry
  namespace: sentry
  labels:
    app: sentry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sentry
  namespace: sentry
  labels:
    app: sentry
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sentry
  namespace: sentry
  labels:
    app: sentry
subjects:
- kind: ServiceAccount
  name: sentry
roleRef:
  kind: Role
  name: sentry
  apiGroup: rbac.authorization.k8s.io 