apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentry-data
  namespace: sentry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard 