apiVersion: v1
kind: ServiceAccount
metadata:
  name: sports-booking-backend
  labels:
    app: sports-booking-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sports-booking-backend
  labels:
    app: sports-booking-backend
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sports-booking-backend
  labels:
    app: sports-booking-backend
subjects:
- kind: ServiceAccount
  name: sports-booking-backend
roleRef:
  kind: Role
  name: sports-booking-backend
  apiGroup: rbac.authorization.k8s.io 